language: go
install:
    - go get code.google.com/p/go-mysql-driver/mysql
    - go get code.google.com/p/go.crypto/pbkdf2
    - go get code.google.com/p/gorilla/pat
    - go get code.google.com/p/gorilla/sessions
    - go get github.com/akrennmair/goconf
after_script:
    - go test -v
    - go test -v -bench='.*'
