CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	login VARCHAR(64) NOT NULL,
	pwhash BINARY(32) NOT NULL,
	salt BINARY(8) NOT NULL,
	UNIQUE(login)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS activity_types (
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	name VARCHAR(128) NOT NULL,
	user_id INTEGER NOT NULL,
	active INTEGER(1) NOT NULL,
	FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS activities (
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	type_id INTEGER NOT NULL,
	timestamp DATETIME NOT NULL,
	user_id INTEGER NOT NULL,
	description TEXT NOT NULL,
	FOREIGN KEY(user_id) REFERENCES users(id),
	FOREIGN KEY(type_id) REFERENCES activity_types(id)
) ENGINE=InnoDB;
